<div align="center">
  <!-- Footer details -->
  <a href="#top"><img src="gfx/topofpage.gif" width="90" height="10" border="0" alt=""></a>
  <hr size="1" width="90%">
  <?php
	$last_modified = filemtime($this_page);
	echo '<p class="footer">This page last updated: ',date("d.m.Y H:i", $last_modified),' by the <a href="mailto:webmaster@scalos.noname.fr">webmaster</a></p>';
  ?>
</div>

</body>
</html>

