/*
** This file was automatically generated by fdtrans 52.1.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifndef INLINE4_SCALOSPLUGIN_H
#define INLINE4_SCALOSPLUGIN_H

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_EMULATION_H
#include <exec/emulation.h>
#endif


#define SCAGetClassInfo() ({ \
	const struct ScaClassInfo * _ret; \
	if (IScalosPlugin != NULL) { \
		_ret = IScalosPlugin->SCAGetClassInfo(); \
	} else { \
		_ret = EmulateTags(ScalosPluginBase, \
			ET_Offset, -30, \
			ET_RegisterA6, ScalosPluginBase, \
			ET_SaveRegs, TRUE, \
			TAG_DONE); \
	} \
	_ret; \
})

#endif

