#ifndef SCALOSPLUGIN_INTERFACE_DEF_H
#define SCALOSPLUGIN_INTERFACE_DEF_H

/*
** This file was machine generated by idltool 52.1.
** Do not edit
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif


struct ScalosPluginIFace
{
	struct InterfaceData Data;

	uint32 APICALL (*Obtain)(struct ScalosPluginIFace *Self);
	uint32 APICALL (*Release)(struct ScalosPluginIFace *Self);
	void APICALL (*Expunge)(struct ScalosPluginIFace *Self);
	struct Interface * APICALL (*Clone)(struct ScalosPluginIFace *Self);
	const struct ScaClassInfo * APICALL (*SCAGetClassInfo)(struct ScalosPluginIFace *Self);
};

#endif /* SCALOSPLUGIN_INTERFACE_DEF_H */
