<div align="center">
  <!-- Footer details -->
  <a href="#top"><img src="gfx/topofpage.gif" width="90" height="10" border="0" alt=""></a>
  <hr size="1" width="90%">
  <script type="text/javascript" language="JavaScript"><!--
    document.write('<p class=\"footer\">This page last updated: '+document.lastModified+' by the <a href=\"mailto:webmaster@scalos.noname.fr\">webmaster<\/a><\/p>');
  //--></script>
  <noscript><p class="footer">This page last updated by the <a href="mailto:webmaster@scalos.noname.fr">webmaster</a></p></noscript>
</div>

</body>
</html>