<script type="text/javascript" language="JavaScript"><!--
  // Populate the navigation frame
  parent.topframe.location.href = 'top_<?php echo $page_nav_doc; ?>.html';
//--></script>

<!-- Form field checking routine -->
<script type="text/javascript" language="JavaScript"><!--
  function CheckField(Field, ErrorMessage)
  {
    if (Field.value.length == 0)
    {
      alert(ErrorMessage); return false;
    }
  }
//--></script>

<!-- Form checking routine -->
<script type="text/javascript" language="JavaScript"><!--
  function CheckFullForm(Form)
  {
    if (CheckField(Form.name, 'You must supply a name/nickname.') == false) return false;
    if (CheckField(Form.email, 'You must supply an e-mail address.') == false) return false;
    if (CheckField(Form.subject, 'You must supply a subject.') == false) return false;
    if (CheckField(Form.details, 'You must supply some details.') == false) return false;
  }
//--></script>
</head>

<body bgcolor="#c4c6db" text="#002244" link="#002244" vlink="#224466">
<a name="top"></a>
<br>
