/*
** This file was automatically generated by fdtrans 51.19.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifndef INLINE4_DTCLASS_H
#define INLINE4_DTCLASS_H

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_EMULATION_H
#include <exec/emulation.h>
#endif

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef INTUITION_CLASSES_H
#include <intuition/classes.h>
#endif
#ifndef INTUITION_CLASSUSR_H
#include <intuition/classusr.h>
#endif

#define ObtainEngine() ({ \
	Class * _ret; \
	if (IDTClass != NULL) { \
		_ret = IDTClass->ObtainEngine(); \
	} else { \
		_ret = (Class *)EmulateTags(DTClassBase, \
			ET_Offset, -30, \
			ET_RegisterA6, DTClassBase, \
			ET_SaveRegs, TRUE, \
			TAG_DONE); \
	} \
	_ret; \
})

#endif

