/*
** This file was automatically generated by fdtrans 52.1.
** Do not edit it by hand. Instead, edit the sfd file
** that was used to generate this file
*/

#ifndef INLINE4_SCALOSPREFSPLUGIN_H
#define INLINE4_SCALOSPREFSPLUGIN_H

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef EXEC_EMULATION_H
#include <exec/emulation.h>
#endif


#define SCAGetPrefsInfo(_which ) ({ \
	ULONG _ret; \
	if (IScalosPrefsPlugin != NULL) { \
		_ret = IScalosPrefsPlugin->SCAGetPrefsInfo(_which ); \
	} else { \
		_ret = EmulateTags(ScalosPrefsPluginBase, \
			ET_Offset, -30, \
			ET_RegisterD0, _which, \
			ET_RegisterA6, ScalosPrefsPluginBase, \
			ET_SaveRegs, TRUE, \
			TAG_DONE); \
	} \
	_ret; \
})

#endif

